modLoader="javafml"
loaderVersion="[52,)"
license="MIT"

[[mods]]
modId="satisfactory"
version="0.0.1"
displayName="Satisfactory Forge"
description='''A Minecraft Forge modpack inspired by Satisfactory, focused on automation and factory building.'''
authors="Yatharth"

[[dependencies.satisfactory]]
modId="forge"
mandatory=true
versionRange="[52.1.0,)"
ordering="NONE"
side="BOTH"
